#!/usr/bin/env python3
"""Bundle the multi-file VoidUI module tree into a single loadstring-ready Lua file.

Run:  python build_bundle.py   (or: py build_bundle.py)
Output: VoidUI.lua  (a self-contained script returned by loadstring)

The bundle rewrites every `require(script.Parent...)` into a lookup against an
in-memory module table, so the result works identically whether you `require`
the folder or `loadstring` the bundle.
"""
import os
import re

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "VoidUI")
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "VoidUI.lua")

# Matches require(script.Parent...X) with no spaces inside the parens.
REQ_RE = re.compile(r'require\((script(?:\.Parent)*(?:\.[A-Za-z_][A-Za-z0-9_]*)+)\)')


def resolve(file_dir_segments, script_expr):
    """Resolve a `script.Parent...X` expression to a dotted module key.

    In Roblox, `script` is the current ModuleScript and `script.Parent` is the
    folder that *contains* it. So for a file living in directory D:
      - `script.Parent`      -> D          (1 .Parent, pop 0)
      - `script.Parent.Parent` -> parent of D (2 .Parent, pop 1)
    i.e. each `.Parent` beyond the first walks one directory up. The remaining
    dotted names are appended to form the final module key (e.g. "Core.Utilities").
    """
    parts = script_expr.split(".")
    assert parts[0] == "script", script_expr
    tail = parts[1:]
    parents = tail.count("Parent")
    suffix = [p for p in tail if p != "Parent"]
    dir_seg = list(file_dir_segments)
    for _ in range(max(0, parents - 1)):
        if dir_seg:
            dir_seg.pop()
    return ".".join(dir_seg + suffix)


def collect_modules():
    modules = {}  # key -> body
    for dirpath, _, files in os.walk(ROOT):
        for name in sorted(files):
            if not name.endswith(".lua"):
                continue
            full = os.path.join(dirpath, name)
            rel = os.path.relpath(full, ROOT).replace(os.sep, "/")
            rel = rel[:-4]  # strip .lua
            rel_segments = rel.split("/")
            # file_dir = the directory that contains this file. For an init.lua,
            # `script` IS the folder, so the dir is the folder name (not empty).
            file_dir = rel_segments[:-1]
            # In Roblox, requiring a folder resolves to its init.lua, so the
            # module key is the folder name (drop the trailing "init").
            key_segments = rel_segments[:]
            if key_segments[-1] == "init":
                key_segments = key_segments[:-1]
            key = ".".join(key_segments) if key_segments else "init"
            with open(full, "r", encoding="utf-8") as fh:
                body = fh.read()
            modules[key] = (file_dir, body)
    return modules


def bundle():
    modules = collect_modules()
    chunks = []
    header = (
        "--! VoidUI single-file bundle (generated by build_bundle.py)\n"
        "-- Load with: local VoidUI = loadstring(game:HttpGet(\".../VoidUI.lua\"))()\n"
        "-- The loader below is environment-agnostic: it works in Synapse X,\n"
        "-- Script-Ware, KRNL, Fluxus, and any executor exposing game/HttpGet.\n"
        "local Modules = {}\n"
        "local Cache = {}\n"
        "local function VoidRequire(key)\n"
        "\tif Cache[key] ~= nil then return Cache[key] end\n"
        "\tlocal mod = Modules[key]\n"
        "\tif not mod then error(\"VoidUI: missing module \" .. tostring(key)) end\n"
        "\tlocal result = mod()\n"
        "\tCache[key] = result\n"
        "\treturn result\n"
        "end\n"
        "-- Environment-agnostic HTTP fetch. Tries every known executor API.\n"
        "local function VoidUI_Fetch(url)\n"
        "\tlocal ok, res\n"
        "\tif typeof(game) == \"Instance\" and game.GetService and game:GetService(\"HttpService\") then\n"
        "\t\tlocal hs = game:GetService(\"HttpService\")\n"
        "\t\tif hs.HttpGet then ok, res = pcall(function() return hs:HttpGet(url) end) end\n"
        "\t\tif not ok and hs.GetAsync then ok, res = pcall(function() return hs:GetAsync(url) end) end\n"
        "\tend\n"
        "\tif not ok and typeof(getexecutorcapabilities) == \"function\" then\n"
        "\t\tlocal ok2, caps = pcall(getexecutorcapabilities)\n"
        "\t\tif ok2 and caps and caps.HttpGet then ok, res = pcall(function() return HttpGet(url) end) end\n"
        "\tend\n"
        "\tif not ok and typeof(HttpGet) == \"function\" then ok, res = pcall(function() return HttpGet(url) end) end\n"
        "\tif not ok and typeof(httpget) == \"function\" then ok, res = pcall(function() return httpget(url) end) end\n"
        "\tif not ok and typeof(request) == \"function\" then\n"
        "\t\tok, res = pcall(function()\n"
        "\t\t\tlocal r = request({ Url = url, Method = \"GET\" })\n"
        "\t\t\treturn r and (r.Body or r.body) or \"\"\n"
        "\t\tend)\n"
        "\tend\n"
        "\tif not ok then error(\"VoidUI: could not fetch \" .. tostring(url)) end\n"
        "\treturn res\n"
        "end\n"
        "-- Environment-agnostic loader (loadstring on most, load on some).\n"
        "local function VoidUI_Load(src)\n"
        "\tlocal fn\n"
        "\tif typeof(loadstring) == \"function\" then fn = loadstring(src) end\n"
        "\tif not fn and typeof(load) == \"function\" then fn = load(src) end\n"
        "\tif not fn then error(\"VoidUI: no loadstring/load available\") end\n"
        "\treturn fn()\n"
        "end\n"
    )
    chunks.append(header)

    for key, value in modules.items():
        file_dir, body = value
        # Directory segments of the requiring file (from the real path).
        # Directory segments of the requiring file, split on '/'.
        def repl(m, _dir=file_dir):
            return 'VoidRequire("%s")' % resolve(_dir, m.group(1))

        new_body = REQ_RE.sub(repl, body)
        chunk = 'Modules["%s"] = function()\n%s\nend\n' % (key, new_body)
        chunks.append(chunk)

    chunks.append('return VoidRequire("init")\n')

    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write("\n".join(chunks))
    print("Wrote %s (%d modules)" % (OUT, len(modules)))


if __name__ == "__main__":
    bundle()
