--! VoidUI single-file bundle (generated by build_bundle.py)
-- Load with: local VoidUI = loadstring(game:HttpGet(".../VoidUI.lua"))()
-- The loader below is environment-agnostic: it works in Synapse X,
-- Script-Ware, KRNL, Fluxus, and any executor exposing game/HttpGet.
local Modules = {}
local Cache = {}
local function VoidRequire(key)
	if Cache[key] ~= nil then return Cache[key] end
	local mod = Modules[key]
	if not mod then error("VoidUI: missing module " .. tostring(key)) end
	local result = mod()
	Cache[key] = result
	return result
end
-- Environment-agnostic HTTP fetch. Tries every known executor API.
local function VoidUI_Fetch(url)
	local ok, res
	if typeof(game) == "Instance" and game.GetService and game:GetService("HttpService") then
		local hs = game:GetService("HttpService")
		if hs.HttpGet then ok, res = pcall(function() return hs:HttpGet(url) end) end
		if not ok and hs.GetAsync then ok, res = pcall(function() return hs:GetAsync(url) end) end
	end
	if not ok and typeof(getexecutorcapabilities) == "function" then
		local ok2, caps = pcall(getexecutorcapabilities)
		if ok2 and caps and caps.HttpGet then ok, res = pcall(function() return HttpGet(url) end) end
	end
	if not ok and typeof(HttpGet) == "function" then ok, res = pcall(function() return HttpGet(url) end) end
	if not ok and typeof(httpget) == "function" then ok, res = pcall(function() return httpget(url) end) end
	if not ok and typeof(request) == "function" then
		ok, res = pcall(function()
			local r = request({ Url = url, Method = "GET" })
			return r and (r.Body or r.body) or ""
		end)
	end
	if not ok then error("VoidUI: could not fetch " .. tostring(url)) end
	return res
end
-- Environment-agnostic loader (loadstring on most, load on some).
local function VoidUI_Load(src)
	local fn
	if typeof(loadstring) == "function" then fn = loadstring(src) end
	if not fn and typeof(load) == "function" then fn = load(src) end
	if not fn then error("VoidUI: no loadstring/load available") end
	return fn()
end

Modules["init"] = function()
local cloneref = (cloneref or clonereference or function(instance)
	return instance
end)

local HttpService = cloneref(game:GetService("HttpService"))
local Players = cloneref(game:GetService("Players"))
local CoreGui = cloneref(game:GetService("CoreGui"))
local RunService = cloneref(game:GetService("RunService"))
local UserInputService = cloneref(game:GetService("UserInputService"))

local Forge = VoidRequire("Core.Forge")
local Themes, ThemeFallbacks = VoidRequire("Themes.Themes")
local Icons = VoidRequire("Assets.Icons")
local WindowModule = VoidRequire("Core.Window")

local ProtectGui = protectgui or (syn and syn.protect_gui) or function() end

local GUIParent = (gethui and gethui()) or CoreGui or Players.LocalPlayer:WaitForChild("PlayerGui")

local VoidUI = {
	Version = "3.0.0",
	Forge = Forge,
	Themes = Themes,
	ThemeFallbacks = ThemeFallbacks,
	Icon = Icons,
	Windows = {},
	CurrentTheme = "Default",
	Accent = Color3.fromHex(Themes.Default.Accent),
	ScreenGui = nil,
	UIScaleObj = nil,
	UIScale = 1,
	OnThemeChange = nil,
}

Forge.Themes = Themes
Forge.ThemeFallbacks = ThemeFallbacks
Forge.Theme = Themes[VoidUI.CurrentTheme]

function VoidUI.GenerateGUID()
	return HttpService:GenerateGUID(false)
end

function VoidUI:SetTheme(Name)
	if not Themes[Name] then
		warn("[VoidUI] Theme not found:", Name)
		return false
	end
	VoidUI.CurrentTheme = Name
	Forge.Apply(Themes[Name])
	if VoidUI.OnThemeChange then
		Forge.Guard(VoidUI.OnThemeChange, Themes[Name], Name)
	end
	for _, Window in ipairs(VoidUI.Windows) do
		if Window.ApplyTheme then
			Window:ApplyTheme(Themes[Name])
		end
	end
	return true
end

function VoidUI:SetAccent(Color)
	VoidUI.Accent = Color
	Themes[VoidUI.CurrentTheme].Accent = Color
	Themes[VoidUI.CurrentTheme].AccentGlow = Color
	Forge.Apply(Themes[VoidUI.CurrentTheme])
	for _, Window in ipairs(VoidUI.Windows) do
		if Window.ApplyTheme then
			Window:ApplyTheme(Themes[VoidUI.CurrentTheme])
		end
	end
end

function VoidUI:CreateWindow(Options)
	Options = Options or {}
	local Window = WindowModule.new(VoidUI, Options)
	table.insert(VoidUI.Windows, Window)
	return Window
end

function VoidUI:Notify(Options)
	Options = Options or {}
	local Window = VoidUI.Windows[1]
	if Window and Window.Notify then
		return Window:Notify(Options)
	end
	warn("[VoidUI] Notify: no window created yet")
	return nil
end

function VoidUI:GetStats()
	return {
		Windows = #VoidUI.Windows,
		Theme = VoidUI.CurrentTheme,
		Version = VoidUI.Version,
	}
end

function VoidUI.new(Options)
	Options = Options or {}

	if not VoidUI.ScreenGui then
		local UIScaleObj = Forge.Make("UIScale", {
			Scale = VoidUI.UIScale,
		})
		VoidUI.UIScaleObj = UIScaleObj

		local ScreenGui = Forge.Make("ScreenGui", {
			Name = "VoidUI",
			Parent = GUIParent,
			IgnoreGuiInset = true,
			ZIndexBehavior = Enum.ZIndexBehavior.Sibling,
			DisplayOrder = 1000,
			ResetOnSpawn = false,
		}, {
			UIScaleObj,
			Forge.Make("Folder", { Name = "Windows" }),
			Forge.Make("Folder", { Name = "Notifications" }),
			Forge.Make("Folder", { Name = "Overlays" }),
		})
		VoidUI.ScreenGui = ScreenGui
		ProtectGui(ScreenGui)
	end

	VoidUI:SetTheme(Options.Theme or "Default")
	if Options.Accent then
		VoidUI:SetAccent(Options.Accent)
	end

	return VoidUI
end

return VoidUI

end

Modules["Assets.Icons"] = function()
local Forge = VoidRequire("Core.Forge")

local RealEnum = Enum
local Enum = setmetatable({}, {
	__index = function(_, Category)
		local Cat = RealEnum[Category]
		if Cat == nil then
			return setmetatable({}, { __index = function() return nil end })
		end
		return setmetatable({}, { __index = function(_, Member)
			return Cat[Member]
		end })
	end,
})

local Icons = {}
Icons.__index = Icons

local Glyphs = {
	Home = "⌂",
	Settings = "⚙",
	Search = "⌕",
	Close = "✕",
	Check = "✓",
	CheckCircle = "✔",
	ChevronDown = "▾",
	ChevronUp = "▴",
	ChevronLeft = "◂",
	ChevronRight = "▸",
	ArrowRight = "→",
	ArrowLeft = "←",
	ArrowUp = "↑",
	ArrowDown = "↓",
	Plus = "＋",
	Minus = "－",
	Star = "★",
	Heart = "♥",
	Bell = "🔔",
	User = "👤",
	Users = "👥",
	Lock = "🔒",
	Unlock = "🔓",
	Eye = "👁",
	EyeOff = "🚫",
	Trash = "🗑",
	Edit = "✎",
	Copy = "⧉",
	Download = "⤓",
	Upload = "⤒",
	Refresh = "↻",
	Play = "▶",
	Pause = "⏸",
	Stop = "⏹",
	Volume = "🔊",
	Mute = "🔇",
	Info = "ℹ",
	Warning = "⚠",
	Error = "⛔",
	Success = "✅",
	Danger = "⛔",
	Sword = "⚔",
	Shield = "🛡",
	Fire = "🔥",
	Zap = "⚡",
	Gear = "⚙",
	Folder = "📁",
	File = "📄",
	Image = "🖼",
	Code = "⟨⟩",
	Terminal = "▷",
	Globe = "🌐",
	Clock = "🕘",
	Key = "🔑",
	Flag = "⚑",
	Bookmark = "🔖",
	Tag = "🏷",
	Link = "🔗",
	Mail = "✉",
	Phone = "☎",
	Camera = "📷",
	Music = "♪",
	Video = "🎬",
	Chart = "📊",
	Grid = "▦",
	List = "☰",
	Menu = "☰",
	Sun = "☀",
	Moon = "🌙",
	Cloud = "☁",
	Bolt = "⚡",
	Diamond = "◆",
	Circle = "●",
	Square = "■",
	Cross = "✕",
	Void = "◈",
	Sparkles = "✦",
	Command = "⌘",
	Filter = "⏷",
	Maximize = "▢",
	Minimize = "▁",
	Pin = "📌",
	Wrench = "🔧",
	Hammer = "🔨",
	Rocket = "🚀",
	Target = "◎",
	Compass = "🧭",
	Layers = "☰",
	Box = "▣",
	Package = "📦",
	Cpu = "🖥",
	Database = "🗄",
	Gauge = "📈",
	Activity = "📈",
	Wifi = "📶",
	Battery = "🔋",
	Power = "⏻",
	Logout = "⏻",
	Login = "⏻",
	Help = "？",
	Question = "？",
	Exclamation = "！",
	PlusCircle = "⊕",
	MinusCircle = "⊖",
	Dot = "•",
	Bullet = "•",
	Record = "⏺",
	Send = "➤",
	Paperclip = "📎",
	Scissors = "✂",
	Printer = "🖨",
	Calendar = "📅",
	Map = "🗺",
	Location = "📍",
	Navigation = "🧭",
	Book = "📖",
	BookMark = "🔖",
	Lightbulb = "💡",
	Flash = "⚡",
	Thunder = "⚡",
	Droplet = "💧",
	Wind = "🌬",
	Snow = "❄",
	Leaf = "🍃",
	Tree = "🌳",
	Flower = "❀",
	Star2 = "✶",
	Crown = "👑",
	Trophy = "🏆",
	Medal = "🏅",
	Gem = "💎",
	Coins = "🪙",
	Credit = "💳",
	Cart = "🛒",
	Bag = "👜",
	Gift = "🎁",
	Heart2 = "❤",
	Smile = "☺",
	Meh = "😐",
	Sad = "☹",
	Angry = "😠",
	Cool = "😎",
	Ghost = "👻",
	Robot = "🤖",
	Alien = "👽",
	Rocket2 = "🚀",
	Bug = "🐛",
	Skull = "💀",
	Eye2 = "👁",
	Ear = "👂",
	Hand = "✋",
	Pointer = "👆",
	Grab = "✊",
	ThumbsUp = "👍",
	ThumbsDown = "👎",
}

function Icons.Create(Name, Color, Size)
	local Glyph = Glyphs[Name] or Glyphs.Void
	local Label = Forge.Make("TextLabel", {
		Text = Glyph,
		TextSize = Size or 18,
		TextColor3 = Color or Color3.fromHex("#E6EAF2"),
		TextXAlignment = Enum.TextXAlignment.Center,
		TextYAlignment = Enum.TextYAlignment.Center,
		BackgroundTransparency = 1,
		Size = UDim2.fromOffset(Size or 18, Size or 18),
		FontFace = Font.fromEnum(Enum.Font.Gotham),
		Skin = {
			TextColor3 = "Text",
		},
	})
	return Label
end

function Icons.Has(Name)
	return Glyphs[Name] ~= nil
end

function Icons.Set(Name, Glyph)
	Glyphs[Name] = Glyph
end

return Icons

end

Modules["Core.Forge"] = function()
local cloneref = (cloneref or clonereference or function(instance)
	return instance
end)

local RunService = cloneref(game:GetService("RunService"))
local TweenService = cloneref(game:GetService("TweenService"))
local UserInputService = cloneref(game:GetService("UserInputService"))

local RealEnum = Enum
local Enum = setmetatable({}, {
	__index = function(_, Category)
		local Cat = RealEnum[Category]
		if Cat == nil then
			return setmetatable({}, { __index = function() return nil end })
		end
		return setmetatable({}, { __index = function(_, Member)
			return Cat[Member]
		end })
	end,
})

local Forge = {
	Font = Enum.Font.Gotham,
	Theme = nil,
	Themes = nil,
	ThemeFallbacks = nil,
	Skins = {},
	ThemeHooks = {},
	Fonts = {},
	UIScale = 1,
	Defaults = {
		ScreenGui = {
			ResetOnSpawn = false,
			ZIndexBehavior = Enum.ZIndexBehavior.Sibling,
		},
		CanvasGroup = {
			BorderSizePixel = 0,
			BackgroundColor3 = Color3.new(1, 1, 1),
		},
		Frame = {
			BorderSizePixel = 0,
			BackgroundColor3 = Color3.new(1, 1, 1),
		},
		TextLabel = {
			BackgroundColor3 = Color3.new(1, 1, 1),
			BorderSizePixel = 0,
			Text = "",
			RichText = true,
			TextColor3 = Color3.new(1, 1, 1),
			TextSize = 14,
			FontFace = Font.fromEnum(Enum.Font.Gotham),
		},
		TextButton = {
			BackgroundColor3 = Color3.new(1, 1, 1),
			BorderSizePixel = 0,
			Text = "",
			AutoButtonColor = false,
			TextColor3 = Color3.new(1, 1, 1),
			TextSize = 14,
			FontFace = Font.fromEnum(Enum.Font.Gotham),
		},
		TextBox = {
			BackgroundColor3 = Color3.new(1, 1, 1),
			BorderColor3 = Color3.new(0, 0, 0),
			ClearTextOnFocus = false,
			Text = "",
			TextColor3 = Color3.new(0, 0, 0),
			TextSize = 14,
			FontFace = Font.fromEnum(Enum.Font.Gotham),
		},
		ImageLabel = {
			BackgroundTransparency = 1,
			BackgroundColor3 = Color3.new(1, 1, 1),
			BorderSizePixel = 0,
		},
		ImageButton = {
			BackgroundColor3 = Color3.new(1, 1, 1),
			BorderSizePixel = 0,
			AutoButtonColor = false,
		},
		UIListLayout = {
			SortOrder = Enum.SortOrder.LayoutOrder,
		},
		UIPadding = {
			PaddingLeft = UDim.new(0, 0),
			PaddingRight = UDim.new(0, 0),
			PaddingTop = UDim.new(0, 0),
			PaddingBottom = UDim.new(0, 0),
		},
		UIStroke = {
			Thickness = 1,
		},
		UICorner = {
			CornerRadius = UDim.new(0, 0),
		},
		ScrollingFrame = {
			ScrollBarImageTransparency = 1,
			BorderSizePixel = 0,
			BackgroundColor3 = Color3.new(1, 1, 1),
			AutomaticCanvasSize = Enum.AutomaticCanvasSize.Y,
			ScrollingDirection = Enum.ScrollingDirection.Y,
			VerticalScrollBarPosition = Enum.VerticalScrollBarPosition.Left,
		},
	},
}

function Forge.Guard(Callback, ...)
	if type(Callback) ~= "function" then
		return
	end
	local Success, Error = pcall(Callback, ...)
	if not Success then
		warn("[VoidUI] Callback error:", Error)
	end
end

function Forge.Make(Name, Properties, Children)
	local Object = Instance.new(Name)

	for Property, Value in next, Forge.Defaults[Name] or {} do
		if Value ~= nil then
			Object[Property] = Value
		end
	end

	for Property, Value in next, Properties or {} do
		if Property ~= "Skin" and Value ~= nil then
			Object[Property] = Value
		end
	end

	for _, Child in next, Children or {} do
		if Child ~= nil then
			Child.Parent = Object
		end
	end

	if Properties and Properties.Skin then
		Forge.Tag(Object, Properties.Skin)
	end
	if Properties and Properties.FontFace then
		Forge.TrackFont(Object)
	end
	return Object
end

function Forge.TrackFont(Object)
	table.insert(Forge.Fonts, Object)
end

function Forge.SetFont(FontEnum)
	Forge.Font = FontEnum
	for _, Obj in next, Forge.Fonts do
		local ok, err = pcall(function()
			Obj.FontFace = Font.fromEnum(FontEnum)
		end)
		if not ok then
			warn("[VoidUI] Font update failed:", err)
		end
	end
end

function Forge.Resolve(Property, Theme)
	local function read(prop, themeTable)
		local value = themeTable[prop]
		if value == nil then
			return nil
		end
		if type(value) == "string" and string.sub(value, 1, 1) == "#" then
			return Color3.fromHex(value)
		end
		if type(value) == "Color3" then
			return value
		end
		if type(value) == "number" then
			return value
		end
		if type(value) == "table" and value.Color and value.Transparency then
			return value
		end
		if type(value) == "function" then
			return value(themeTable)
		end
		return value
	end

	local value = read(Property, Theme)
	if value ~= nil then
		if type(value) == "string" and string.sub(value, 1, 1) ~= "#" then
			local referenced = Forge.Resolve(value, Theme)
			if referenced ~= nil then
				return referenced
			end
		else
			return value
		end
	end

	local fallback = Forge.ThemeFallbacks and Forge.ThemeFallbacks[Property]
	if fallback ~= nil then
		if type(fallback) == "string" and string.sub(fallback, 1, 1) ~= "#" then
			return Forge.Resolve(fallback, Theme)
		else
			return read(Property, { [Property] = fallback })
		end
	end

	value = read(Property, Forge.Themes and Forge.Themes["Default"] or {})
	if value ~= nil then
		if type(value) == "string" and string.sub(value, 1, 1) ~= "#" then
			local referenced = Forge.Resolve(value, Forge.Themes and Forge.Themes["Default"] or {})
			if referenced ~= nil then
				return referenced
			end
		else
			return value
		end
	end

	return nil
end

function Forge.Tag(Object, Properties, skipUpdate)
	if Forge.Skins[Object] then
		for prop, value in pairs(Properties) do
			Forge.Skins[Object].Properties[prop] = value
		end
	else
		Forge.Skins[Object] = { Object = Object, Properties = Properties }
	end

	if not skipUpdate then
		Forge.Refresh(Object, false)
	end
	return Object
end

function Forge.Refresh(Object, ThemeChanged)
	local Theme = Forge.Theme
	if not Theme then
		return
	end
	if Object then
		local data = Forge.Skins[Object]
		if not data then
			return
		end
		for prop, value in pairs(data.Properties) do
			local ThemeValue = Forge.Resolve(value, Theme)
			if ThemeValue ~= nil then
				local ok, err = pcall(function()
					Object[prop] = ThemeValue
				end)
				if not ok then
					warn("[VoidUI] Theme apply failed for", prop, err)
				end
			end
		end
		return
	end
	for _, data in pairs(Forge.Skins) do
		for prop, value in pairs(data.Properties) do
			local ThemeValue = Forge.Resolve(value, Theme)
			if ThemeValue ~= nil then
				pcall(function()
					data.Object[prop] = ThemeValue
				end)
			end
		end
	end
end

function Forge.Apply(Theme)
	local PreviousTheme = Forge.Theme
	Forge.Theme = Theme
	Forge.Refresh(nil, true)

	for _, Callback in next, Forge.ThemeHooks do
		Forge.Guard(Callback, Theme, PreviousTheme)
	end
end

function Forge.OnTheme(Callback)
	table.insert(Forge.ThemeHooks, Callback)
end

function Forge.Tween(Object, Time, Properties, ...)
	return TweenService:Create(Object, TweenInfo.new(Time, ...), Properties)
end

function Forge.Spring(Object, Property, Target, Options)
	Options = Options or {}
	local Tween = Forge.Tween(Object, Options.Duration or 0.3, { [Property] = Target }, Enum.EasingStyle.Quad, Enum.EasingDirection.Out)
	Tween:Play()
	return Tween
end

return Forge

end

Modules["Core.Tab"] = function()
local Forge = VoidRequire("Core.Forge")
local Icons = VoidRequire("Assets.Icons")

local RealEnum = Enum
local Enum = setmetatable({}, {
	__index = function(_, Category)
		local Cat = RealEnum[Category]
		if Cat == nil then
			return setmetatable({}, { __index = function() return nil end })
		end
		return setmetatable({}, { __index = function(_, Member)
			return Cat[Member]
		end })
	end,
})

local Tab = {}
Tab.__index = Tab

function Tab.new(Window, Options)
	Options = Options or {}
	local self = setmetatable({}, Tab)
	self.Window = Window
	self.Title = Options.Title or "Tab"
	self.Icon = Options.Icon or "Circle"
	self.Selected = false
	self.Widgets = {}

	local Theme = Window.VoidUI.Themes[Window.VoidUI.CurrentTheme]

	local Button = Forge.Make("TextButton", {
		Name = "TabButton",
		Size = UDim2.new(1, -16, 0, 36),
		BackgroundTransparency = 1,
		Text = "",
		Parent = Window.Sidebar,
	}, {
		Forge.Make("UICorner", { CornerRadius = UDim.new(0, 8) }),
		Forge.Make("UIListLayout", {
			FillDirection = Enum.FillDirection.Horizontal,
			Padding = UDim.new(0, 10),
			VerticalAlignment = Enum.VerticalAlignment.Center,
			SortOrder = Enum.SortOrder.LayoutOrder,
		}),
		Forge.Make("UIPadding", { PaddingLeft = UDim.new(0, 12) }),
		Icons.Create(self.Icon, Theme.TextDim, 18),
		Forge.Make("TextLabel", {
			Text = self.Title,
			TextSize = 14,
			TextXAlignment = Enum.TextXAlignment.Left,
			TextColor3 = Theme.TextDim,
			Size = UDim2.new(1, -40, 1, 0),
			FontFace = Font.fromEnum(Enum.Font.Gotham),
			Skin = { TextColor3 = "TextDim" },
		}),
	})
	Button.MouseButton1Click:Connect(function()
		Window:SelectTab(self)
	end)
	self.Button = Button

	local Section = Forge.Make("Frame", {
		Name = "TabContent",
		BackgroundTransparency = 1,
		BorderSizePixel = 0,
		Size = UDim2.new(1, 0, 0, 0),
		AutomaticSize = Enum.AutomaticSize.Y,
		Visible = false,
		Parent = Window.Content,
	}, {
		Forge.Make("UIListLayout", {
			FillDirection = Enum.FillDirection.Vertical,
			Padding = UDim.new(0, 8),
			SortOrder = Enum.SortOrder.LayoutOrder,
		}),
	})
	self.Section = Section

	return self
end

function Tab:Select()
	self.Selected = true
	self.Section.Visible = true
	local Theme = self.Window.VoidUI.Themes[self.Window.VoidUI.CurrentTheme]
	Forge.Guard(function()
		self.Button.BackgroundTransparency = 0.85
		self.Button.BackgroundColor3 = Theme.SurfaceHover
	end)
end

function Tab:Deselect()
	self.Selected = false
	self.Section.Visible = false
	Forge.Guard(function()
		self.Button.BackgroundTransparency = 1
	end)
end

function Tab:_Row(Title, Desc)
	local Theme = self.Window.VoidUI.Themes[self.Window.VoidUI.CurrentTheme]
	local Row = Forge.Make("Frame", {
		Size = UDim2.new(1, 0, 0, Desc and 46 or 36),
		BackgroundTransparency = 1,
		Parent = self.Section,
	}, {
		Forge.Make("UIListLayout", {
			FillDirection = Enum.FillDirection.Vertical,
			Padding = UDim.new(0, 2),
			SortOrder = Enum.SortOrder.LayoutOrder,
		}),
		Forge.Make("TextLabel", {
			Text = Title or "",
			TextSize = 14,
			TextXAlignment = Enum.TextXAlignment.Left,
			TextColor3 = Theme.Text,
			Size = UDim2.new(1, 0, 0, Desc and 18 or 36),
			FontFace = Font.fromEnum(Enum.Font.Gotham),
			Skin = { TextColor3 = "Text" },
		}),
	})
	if Desc then
		Forge.Make("TextLabel", {
			Text = Desc,
			TextSize = 12,
			TextXAlignment = Enum.TextXAlignment.Left,
			TextColor3 = Theme.TextDim,
			Size = UDim2.new(1, 0, 0, 16),
			FontFace = Font.fromEnum(Enum.Font.Gotham),
			Skin = { TextColor3 = "TextDim" },
			Parent = Row,
		})
	end
	return Row
end

function Tab:CreateSection(Options)
	Options = Options or {}
	local Theme = self.Window.VoidUI.Themes[self.Window.VoidUI.CurrentTheme]
	local Section = Forge.Make("Frame", {
		Size = UDim2.new(1, 0, 0, 30),
		BackgroundTransparency = 1,
		Parent = self.Section,
	}, {
		Forge.Make("UIListLayout", {
			FillDirection = Enum.FillDirection.Horizontal,
			Padding = UDim.new(0, 8),
			VerticalAlignment = Enum.VerticalAlignment.Center,
			SortOrder = Enum.SortOrder.LayoutOrder,
		}),
		Forge.Make("TextLabel", {
			Text = Options.Title or "Section",
			TextSize = 13,
			TextXAlignment = Enum.TextXAlignment.Left,
			TextColor3 = Theme.Accent,
			Size = UDim2.new(0, 0, 1, 0),
			FontFace = Font.fromEnum(Enum.Font.Gotham),
			Skin = { TextColor3 = "Accent" },
		}),
		Forge.Make("Frame", {
			BackgroundColor3 = Theme.Border,
			Size = UDim2.new(1, -10, 0, 1),
			Skin = { BackgroundColor3 = "Border" },
		}),
	})
	return Section
end

function Tab:CreateDivider(Options)
	Options = Options or {}
	local Theme = self.Window.VoidUI.Themes[self.Window.VoidUI.CurrentTheme]
	local Div = Forge.Make("Frame", {
		Size = UDim2.new(1, 0, 0, 1),
		BackgroundColor3 = Theme.Border,
		Parent = self.Section,
		Skin = { BackgroundColor3 = "Border" },
	})
	return Div
end

function Tab:CreateLabel(Options)
	Options = Options or {}
	local Theme = self.Window.VoidUI.Themes[self.Window.VoidUI.CurrentTheme]
	local Label = Forge.Make("TextLabel", {
		Text = Options.Title or "",
		TextSize = 14,
		TextXAlignment = Enum.TextXAlignment.Left,
		TextColor3 = Theme.Text,
		Size = UDim2.new(1, 0, 0, 24),
		FontFace = Font.fromEnum(Enum.Font.Gotham),
		Parent = self.Section,
		Skin = { TextColor3 = "Text" },
	})
	return Label
end

function Tab:CreateParagraph(Options)
	Options = Options or {}
	local Theme = self.Window.VoidUI.Themes[self.Window.VoidUI.CurrentTheme]
	local Para = Forge.Make("Frame", {
		Size = UDim2.new(1, 0, 0, 60),
		BackgroundColor3 = Theme.Surface,
		Parent = self.Section,
		Skin = { BackgroundColor3 = "Surface" },
	}, {
		Forge.Make("UICorner", { CornerRadius = UDim.new(0, 10) }),
		Forge.Make("UIListLayout", {
			FillDirection = Enum.FillDirection.Vertical,
			Padding = UDim.new(0, 4),
			SortOrder = Enum.SortOrder.LayoutOrder,
		}),
		Forge.Make("UIPadding", { PaddingLeft = UDim.new(0, 12), PaddingRight = UDim.new(0, 12), PaddingTop = UDim.new(0, 10), PaddingBottom = UDim.new(0, 10) }),
		Forge.Make("TextLabel", {
			Text = Options.Title or "",
			TextSize = 14,
			TextXAlignment = Enum.TextXAlignment.Left,
			TextColor3 = Theme.Text,
			Size = UDim2.new(1, 0, 0, 18),
			FontFace = Font.fromEnum(Enum.Font.Gotham),
			Skin = { TextColor3 = "Text" },
		}),
		Forge.Make("TextLabel", {
			Text = Options.Content or "",
			TextSize = 12,
			TextXAlignment = Enum.TextXAlignment.Left,
			TextColor3 = Theme.TextDim,
			Size = UDim2.new(1, 0, 0, 28),
			TextWrapped = true,
			FontFace = Font.fromEnum(Enum.Font.Gotham),
			Skin = { TextColor3 = "TextDim" },
		}),
	})
	return Para
end

function Tab:CreateToggle(Options)
	Options = Options or {}
	local Theme = self.Window.VoidUI.Themes[self.Window.VoidUI.CurrentTheme]
	local Value = Options.Default or false
	local Callback = Options.Callback or function() end

	local Row = self:_Row(Options.Title, Options.Description)
	local Control = Forge.Make("Frame", {
		Size = UDim2.new(1, 0, 0, 24),
		BackgroundTransparency = 1,
		Parent = Row,
	}, {
		Forge.Make("UIListLayout", {
			FillDirection = Enum.FillDirection.Horizontal,
			Padding = UDim.new(0, 0),
			VerticalAlignment = Enum.VerticalAlignment.Center,
			HorizontalAlignment = Enum.HorizontalAlignment.Right,
			SortOrder = Enum.SortOrder.LayoutOrder,
		}),
	})

	local Knob = Forge.Make("Frame", {
		Name = "Knob",
		Size = UDim2.fromOffset(16, 16),
		BackgroundColor3 = Color3.fromHex("#FFFFFF"),
		Position = Value and UDim2.new(1, -19, 0.5, 0) or UDim2.new(0, 3, 0.5, 0),
		AnchorPoint = Vector2.new(0, 0.5),
	})
	local Track = Forge.Make("TextButton", {
		Size = UDim2.fromOffset(40, 22),
		BackgroundColor3 = Value and Theme.Accent or Theme.SurfaceHover,
		Text = "",
		Parent = Control,
		Skin = { BackgroundColor3 = Value and "Accent" or "SurfaceHover" },
	}, {
		Forge.Make("UICorner", { CornerRadius = UDim.new(1, 0) }),
		Knob,
	})

	local function SetState(newVal)
		Value = newVal
		Forge.Guard(function()
			Track.BackgroundColor3 = Value and Theme.Accent or Theme.SurfaceHover
			Knob.Position = Value and UDim2.new(1, -19, 0.5, 0) or UDim2.new(0, 3, 0.5, 0)
		end)
		Forge.Guard(Callback, Value)
	end

	Track.MouseButton1Click:Connect(function()
		SetState(not Value)
	end)

	local api = {
		Set = function(_, v) SetState(v) end,
		Get = function() return Value end,
		Instance = Row,
	}
	return api
end

function Tab:CreateSlider(Options)
	Options = Options or {}
	local Theme = self.Window.VoidUI.Themes[self.Window.VoidUI.CurrentTheme]
	local Min = Options.Min or 0
	local Max = Options.Max or 100
	local Value = Options.Default or Min
	local Callback = Options.Callback or function() end
	local Decimal = Options.Decimal or 0

	local Row = self:_Row(Options.Title, Options.Description)
	local Control = Forge.Make("Frame", {
		Size = UDim2.new(1, 0, 0, 26),
		BackgroundTransparency = 1,
		Parent = Row,
	}, {
		Forge.Make("UIListLayout", {
			FillDirection = Enum.FillDirection.Horizontal,
			Padding = UDim.new(0, 10),
			VerticalAlignment = Enum.VerticalAlignment.Center,
			SortOrder = Enum.SortOrder.LayoutOrder,
		}),
	})

	local Fill = Forge.Make("Frame", {
		Name = "Fill",
		Size = UDim2.new(math.clamp((Value - Min) / (Max - Min), 0, 1), 0, 1, 0),
		BackgroundColor3 = Theme.Accent,
		Skin = { BackgroundColor3 = "Accent" },
	}, {
		Forge.Make("UICorner", { CornerRadius = UDim.new(1, 0) }),
	})
	local Bar = Forge.Make("Frame", {
		Size = UDim2.new(1, -60, 0, 6),
		BackgroundColor3 = Theme.SurfaceHover,
		Parent = Control,
		Skin = { BackgroundColor3 = "SurfaceHover" },
	}, {
		Forge.Make("UICorner", { CornerRadius = UDim.new(1, 0) }),
		Fill,
	})

	local ValueLabel = Forge.Make("TextLabel", {
		Text = tostring(Value),
		TextSize = 13,
		TextXAlignment = Enum.TextXAlignment.Right,
		TextColor3 = Theme.Text,
		Size = UDim2.new(0, 50, 1, 0),
		FontFace = Font.fromEnum(Enum.Font.Gotham),
		Skin = { TextColor3 = "Text" },
		Parent = Control,
	})

	local function SetValue(newVal)
		newVal = math.clamp(newVal, Min, Max)
		if Decimal > 0 then
			newVal = math.floor(newVal * (10 ^ Decimal) + 0.5) / (10 ^ Decimal)
		else
			newVal = math.floor(newVal + 0.5)
		end
		Value = newVal
		Forge.Guard(function()
			Fill.Size = UDim2.new(math.clamp((Value - Min) / (Max - Min), 0, 1), 0, 1, 0)
			ValueLabel.Text = tostring(Value)
		end)
		Forge.Guard(Callback, Value)
	end

	local dragging
	Bar.InputBegan:Connect(function(input)
		if input.UserInputType == Enum.UserInputType.MouseButton1 or input.UserInputType == Enum.UserInputType.Touch then
			dragging = true
		end
	end)
	Bar.InputChanged:Connect(function(input)
		if dragging and (input.UserInputType == Enum.UserInputType.MouseMovement or input.UserInputType == Enum.UserInputType.Touch) then
			local absPos = Bar.AbsolutePosition
			local absSize = Bar.AbsoluteSize
			local ratio = math.clamp((input.Position.X - absPos.X) / absSize.X, 0, 1)
			SetValue(Min + ratio * (Max - Min))
		end
	end)
	Bar.InputEnded:Connect(function(input)
		if input.UserInputType == Enum.UserInputType.MouseButton1 or input.UserInputType == Enum.UserInputType.Touch then
			dragging = false
		end
	end)

	local api = {
		Set = function(_, v) SetValue(v) end,
		Get = function() return Value end,
		Instance = Row,
	}
	return api
end

function Tab:CreateDropdown(Options)
	Options = Options or {}
	local Theme = self.Window.VoidUI.Themes[self.Window.VoidUI.CurrentTheme]
	local Items = Options.Options or {}
	local Multi = Options.Multi or false
	local Value
	if Multi then
		Value = (type(Options.Default) == "table") and Options.Default or {}
	else
		Value = Options.Default or Items[1] or nil
	end
	local Callback = Options.Callback or function() end

	local Row = self:_Row(Options.Title, Options.Description)
	local Control = Forge.Make("Frame", {
		Size = UDim2.new(1, 0, 0, 30),
		BackgroundColor3 = Theme.Surface,
		Parent = Row,
		Skin = { BackgroundColor3 = "Surface" },
	}, {
		Forge.Make("UICorner", { CornerRadius = UDim.new(0, 8) }),
		Forge.Make("UIListLayout", {
			FillDirection = Enum.FillDirection.Horizontal,
			Padding = UDim.new(0, 8),
			VerticalAlignment = Enum.VerticalAlignment.Center,
			SortOrder = Enum.SortOrder.LayoutOrder,
		}),
		Forge.Make("UIPadding", { PaddingLeft = UDim.new(0, 10), PaddingRight = UDim.new(0, 10) }),
		Forge.Make("TextLabel", {
			Name = "Current",
			Text = Multi and (#Value > 0 and table.concat(Value, ", ") or "None") or tostring(Value or "None"),
			TextSize = 13,
			TextXAlignment = Enum.TextXAlignment.Left,
			TextColor3 = Theme.Text,
			Size = UDim2.new(1, -24, 1, 0),
			FontFace = Font.fromEnum(Enum.Font.Gotham),
			Skin = { TextColor3 = "Text" },
		}),
		Icons.Create("ChevronDown", Theme.TextDim, 16),
	})

	local function SetValue(newVal)
		if Multi then
			Value = (type(newVal) == "table") and newVal or { newVal }
		else
			Value = newVal
		end
		Forge.Guard(function()
			Control.Current.Text = Multi and (#Value > 0 and table.concat(Value, ", ") or "None") or tostring(Value or "None")
		end)
		Forge.Guard(Callback, Value)
	end

	Control.MouseButton1Click:Connect(function()
		if Multi then
			local first = Items[1]
			if table.find(Value, first) then
				table.remove(Value, table.find(Value, first))
			else
				table.insert(Value, first)
			end
			SetValue(Value)
		else
			local idx = 1
			for i, v in ipairs(Items) do
				if v == Value then idx = i end
			end
			SetValue(Items[idx % #Items + 1])
		end
	end)

	local api = {
		Set = function(_, v) SetValue(v) end,
		Get = function() return Value end,
		Instance = Row,
	}
	return api
end

function Tab:CreateColorPicker(Options)
	Options = Options or {}
	local Theme = self.Window.VoidUI.Themes[self.Window.VoidUI.CurrentTheme]
	local Value = Options.Default or Color3.fromHex("#FFFFFF")
	local Callback = Options.Callback or function() end

	local Row = self:_Row(Options.Title, Options.Description)
	local Swatch = Forge.Make("TextButton", {
		Size = UDim2.fromOffset(28, 28),
		BackgroundColor3 = Value,
		Text = "",
		Parent = Row,
	}, {
		Forge.Make("UICorner", { CornerRadius = UDim.new(0, 6) }),
	})
	Swatch.MouseButton1Click:Connect(function()
		local palette = { Color3.fromHex("#FF5C7A"), Color3.fromHex("#5B8DEF"), Color3.fromHex("#34D399"), Color3.fromHex("#B57CFF"), Color3.fromHex("#FFD166") }
		local next = palette[(table.find(palette, Value) or 0) % #palette + 1]
		Value = next
		Forge.Guard(function() Swatch.BackgroundColor3 = Value end)
		Forge.Guard(Callback, Value)
	end)

	local api = {
		Set = function(_, v) Value = v; Forge.Guard(function() Swatch.BackgroundColor3 = v end) end,
		Get = function() return Value end,
		Instance = Row,
	}
	return api
end

function Tab:CreateKeybind(Options)
	Options = Options or {}
	local Theme = self.Window.VoidUI.Themes[self.Window.VoidUI.CurrentTheme]
	local Value = Options.Default or Enum.KeyCode.RightShift
	local Callback = Options.Callback or function() end

	local Row = self:_Row(Options.Title, Options.Description)
	local Button = Forge.Make("TextButton", {
		Size = UDim2.fromOffset(120, 28),
		BackgroundColor3 = Theme.Surface,
		Text = tostring(Value),
		TextSize = 13,
		TextColor3 = Theme.Text,
		Parent = Row,
		FontFace = Font.fromEnum(Enum.Font.Gotham),
		Skin = { BackgroundColor3 = "Surface", TextColor3 = "Text" },
	}, {
		Forge.Make("UICorner", { CornerRadius = UDim.new(0, 6) }),
	})
	Button.MouseButton1Click:Connect(function()
		Button.Text = "Press a key..."
		local conn
		conn = game:GetService("UserInputService").InputBegan:Connect(function(input, gp)
			if gp then return end
			if input.UserInputType == Enum.UserInputType.Keyboard then
				Value = input.KeyCode
				Forge.Guard(function() Button.Text = tostring(Value) end)
				Forge.Guard(Callback, Value)
				conn:Disconnect()
			end
		end)
	end)

	local api = {
		Set = function(_, v) Value = v; Forge.Guard(function() Button.Text = tostring(v) end) end,
		Get = function() return Value end,
		Instance = Row,
	}
	return api
end

function Tab:CreateTextbox(Options)
	Options = Options or {}
	local Theme = self.Window.VoidUI.Themes[self.Window.VoidUI.CurrentTheme]
	local Value = Options.Default or ""
	local Callback = Options.Callback or function() end

	local Row = self:_Row(Options.Title, Options.Description)
	local Box = Forge.Make("TextBox", {
		Size = UDim2.new(1, 0, 0, 30),
		BackgroundColor3 = Theme.Surface,
		Text = Value,
		PlaceholderText = Options.Placeholder or "",
		TextSize = 13,
		TextColor3 = Theme.Text,
		ClearTextOnFocus = false,
		Parent = Row,
		FontFace = Font.fromEnum(Enum.Font.Gotham),
		Skin = { BackgroundColor3 = "Surface", TextColor3 = "Text" },
	}, {
		Forge.Make("UICorner", { CornerRadius = UDim.new(0, 8) }),
		Forge.Make("UIPadding", { PaddingLeft = UDim.new(0, 10) }),
	})
	Box.FocusLost:Connect(function(enter)
		Value = Box.Text
		Forge.Guard(Callback, Value, enter)
	end)

	local api = {
		Set = function(_, v) Value = v; Forge.Guard(function() Box.Text = v end) end,
		Get = function() return Value end,
		Instance = Row,
	}
	return api
end

function Tab:CreateButton(Options)
	Options = Options or {}
	local Theme = self.Window.VoidUI.Themes[self.Window.VoidUI.CurrentTheme]
	local Callback = Options.Callback or function() end

	local Button = Forge.Make("TextButton", {
		Size = UDim2.new(1, 0, 0, 34),
		BackgroundColor3 = Theme.Accent,
		Text = Options.Title or "Button",
		TextSize = 14,
		TextColor3 = Color3.fromHex("#0E1116"),
		Parent = self.Section,
		FontFace = Font.fromEnum(Enum.Font.Gotham),
		Skin = { BackgroundColor3 = "Accent" },
	}, {
		Forge.Make("UICorner", { CornerRadius = UDim.new(0, 8) }),
	})
	Button.MouseButton1Click:Connect(function()
		Forge.Guard(Callback)
	end)

	local api = { Instance = Button }
	return api
end

return Tab

end

Modules["Core.Window"] = function()
local Forge = VoidRequire("Core.Forge")
local Icons = VoidRequire("Assets.Icons")
local TabModule = VoidRequire("Core.Tab")

local RealEnum = Enum
local Enum = setmetatable({}, {
	__index = function(_, Category)
		local Cat = RealEnum[Category]
		if Cat == nil then
			return setmetatable({}, { __index = function() return nil end })
		end
		return setmetatable({}, { __index = function(_, Member)
			return Cat[Member]
		end })
	end,
})

local Window = {}
Window.__index = Window

function Window.new(VoidUI, Config)
	Config = Config or {}
	local self = setmetatable({}, Window)

	self.VoidUI = VoidUI
	self.Title = Config.Title or "VoidUI"
	self.Icon = Config.Icon or "Void"
	self.Subtitle = Config.Subtitle or ""
	self.Size = Config.Size or UDim2.fromOffset(620, 440)
	self.Position = Config.Position or UDim2.fromScale(0.5, 0.5)
	self.Resizable = Config.Resizable ~= false
	self.Draggable = Config.Draggable ~= false
	self.Minimized = false
	self.Maximized = false
	self.Closed = false
	self.Tabs = {}
	self.ActiveTab = nil
	self.Notifications = {}
	self.ZIndex = 100

	local WindowsFolder = VoidUI.ScreenGui:FindFirstChild("Windows")
	local NotifFolder = VoidUI.ScreenGui:FindFirstChild("Notifications")

	self:_Build(WindowsFolder, NotifFolder)
	return self
end

function Window:_Build(WindowsFolder, NotifFolder)
	local Theme = self.VoidUI.CurrentTheme and self.VoidUI.Themes[self.VoidUI.CurrentTheme] or self.VoidUI.Themes.Default

	local Main = Forge.Make("Frame", {
		Name = "Window",
		BackgroundColor3 = Theme.Background,
		BorderSizePixel = 0,
		Size = self.Size,
		Position = self.Position,
		AnchorPoint = Vector2.new(0.5, 0.5),
		ZIndex = self.ZIndex,
		ClipsDescendants = true,
		Parent = WindowsFolder,
		Skin = {
			BackgroundColor3 = "Background",
		},
	}, {
		Forge.Make("UICorner", { CornerRadius = UDim.new(0, Theme.RadiusLarge or 18) }),
		Forge.Make("UIStroke", {
			Color = Theme.Border,
			Thickness = 1,
			Transparency = 0.4,
			Skin = { Color = "Border" },
		}),
	})

	local Header = Forge.Make("Frame", {
		Name = "Header",
		BackgroundColor3 = Theme.BackgroundElevated,
		BorderSizePixel = 0,
		Size = UDim2.new(1, 0, 0, Theme.HeaderHeight or 52),
		ZIndex = self.ZIndex + 1,
		Parent = Main,
		Skin = { BackgroundColor3 = "BackgroundElevated" },
	}, {
		Forge.Make("UICorner", { CornerRadius = UDim.new(0, Theme.RadiusLarge or 18) }),
	})

	local HeaderClip = Forge.Make("Frame", {
		BackgroundTransparency = 1,
		BorderSizePixel = 0,
		Size = UDim2.new(1, 0, 0, Theme.RadiusLarge or 18),
		ClipsDescendants = true,
		ZIndex = self.ZIndex + 1,
		Parent = Header,
	})

	local HeaderContent = Forge.Make("Frame", {
		BackgroundTransparency = 1,
		BorderSizePixel = 0,
		Size = UDim2.new(1, 0, 1, 0),
		ZIndex = self.ZIndex + 2,
		Parent = Header,
	}, {
		Forge.Make("UIListLayout", {
			FillDirection = Enum.FillDirection.Horizontal,
			Padding = UDim.new(0, 12),
			VerticalAlignment = Enum.VerticalAlignment.Center,
			SortOrder = Enum.SortOrder.LayoutOrder,
		}),
		Forge.Make("UIPadding", { PaddingLeft = UDim.new(0, 16), PaddingRight = UDim.new(0, 12) }),
	})

	local IconFrame = Icons.Create(self.Icon, Theme.Accent, 22)
	IconFrame.LayoutOrder = 1
	IconFrame.Parent = HeaderContent

	local TitleBlock = Forge.Make("Frame", {
		BackgroundTransparency = 1,
		BorderSizePixel = 0,
		Size = UDim2.new(1, -200, 1, 0),
		ZIndex = self.ZIndex + 2,
		Parent = HeaderContent,
	}, {
		Forge.Make("UIListLayout", {
			FillDirection = Enum.FillDirection.Vertical,
			Padding = UDim.new(0, 0),
			VerticalAlignment = Enum.VerticalAlignment.Center,
			SortOrder = Enum.SortOrder.LayoutOrder,
		}),
		Forge.Make("TextLabel", {
			Name = "Title",
			Text = self.Title,
			TextSize = 16,
			TextXAlignment = Enum.TextXAlignment.Left,
			TextColor3 = Theme.Text,
			Size = UDim2.new(1, 0, 0, 18),
			FontFace = Font.fromEnum(Enum.Font.Gotham),
			Skin = { TextColor3 = "Text" },
		}),
		Forge.Make("TextLabel", {
			Name = "Subtitle",
			Text = self.Subtitle,
			TextSize = 12,
			TextXAlignment = Enum.TextXAlignment.Left,
			TextColor3 = Theme.TextDim,
			Size = UDim2.new(1, 0, 0, 14),
			Visible = #self.Subtitle > 0,
			Skin = { TextColor3 = "TextDim" },
		}),
	})

	local Controls = Forge.Make("Frame", {
		BackgroundTransparency = 1,
		BorderSizePixel = 0,
		Size = UDim2.new(0, 96, 1, 0),
		ZIndex = self.ZIndex + 2,
		Parent = HeaderContent,
	}, {
		Forge.Make("UIListLayout", {
			FillDirection = Enum.FillDirection.Horizontal,
			Padding = UDim.new(0, 6),
			VerticalAlignment = Enum.VerticalAlignment.Center,
			HorizontalAlignment = Enum.HorizontalAlignment.Right,
			SortOrder = Enum.SortOrder.LayoutOrder,
		}),
	})

	self:_CreateControlButton(Controls, "Minus", function()
		self:ToggleMinimize()
	end, Theme.TextDim)
	self:_CreateControlButton(Controls, "Square", function()
		self:ToggleMaximize()
	end, Theme.TextDim)
	self:_CreateControlButton(Controls, "Close", function()
		self:Close()
	end, Theme.Danger)

	local Body = Forge.Make("Frame", {
		Name = "Body",
		BackgroundTransparency = 1,
		BorderSizePixel = 0,
		Size = UDim2.new(1, 0, 1, -(Theme.HeaderHeight or 52)),
		Position = UDim2.new(0, 0, 0, Theme.HeaderHeight or 52),
		ZIndex = self.ZIndex + 1,
		Parent = Main,
	})

	local Sidebar = Forge.Make("Frame", {
		Name = "Sidebar",
		BackgroundColor3 = Theme.Surface,
		BorderSizePixel = 0,
		Size = UDim2.new(0, Theme.SidebarWidth or 200, 1, 0),
		ZIndex = self.ZIndex + 1,
		Parent = Body,
		Skin = { BackgroundColor3 = "Surface" },
	}, {
		Forge.Make("UICorner", { CornerRadius = UDim.new(0, Theme.Radius or 12) }),
		Forge.Make("UIListLayout", {
			FillDirection = Enum.FillDirection.Vertical,
			Padding = UDim.new(0, 6),
			HorizontalAlignment = Enum.HorizontalAlignment.Center,
			SortOrder = Enum.SortOrder.LayoutOrder,
		}),
		Forge.Make("UIPadding", { PaddingTop = UDim.new(0, 10), PaddingBottom = UDim.new(0, 10) }),
	})

	local Content = Forge.Make("ScrollingFrame", {
		Name = "Content",
		BackgroundTransparency = 1,
		BorderSizePixel = 0,
		Size = UDim2.new(1, -(Theme.SidebarWidth or 200), 1, 0),
		Position = UDim2.new(0, Theme.SidebarWidth or 200, 0, 0),
		ZIndex = self.ZIndex + 1,
		ScrollBarThickness = 4,
		ScrollBarImageColor3 = Theme.Scrollbar,
		CanvasSize = UDim2.new(0, 0, 0, 0),
		Parent = Body,
		Skin = { ScrollBarImageColor3 = "Scrollbar" },
	}, {
		Forge.Make("UIListLayout", {
			FillDirection = Enum.FillDirection.Vertical,
			Padding = UDim.new(0, 8),
			SortOrder = Enum.SortOrder.LayoutOrder,
		}),
		Forge.Make("UIPadding", { PaddingLeft = UDim.new(0, 14), PaddingRight = UDim.new(0, 14), PaddingTop = UDim.new(0, 12), PaddingBottom = UDim.new(0, 12) }),
	})

	self.Main = Main
	self.Header = Header
	self.Body = Body
	self.Sidebar = Sidebar
	self.Content = Content
	self.NotifFolder = NotifFolder

	self:_EnableDrag()
end

function Window:_CreateControlButton(Parent, IconName, Callback, Color)
	local Button = Forge.Make("TextButton", {
		Size = UDim2.fromOffset(28, 28),
		BackgroundTransparency = 1,
		Text = "",
		Parent = Parent,
	}, {
		Icons.Create(IconName, Color, 16),
	})
	Button.MouseButton1Click:Connect(function()
		Forge.Guard(Callback)
	end)
	Button.MouseEnter:Connect(function()
		Forge.Guard(function()
			Button.BackgroundTransparency = 0.9
			Button.BackgroundColor3 = Color
		end)
	end)
	Button.MouseLeave:Connect(function()
		Forge.Guard(function()
			Button.BackgroundTransparency = 1
		end)
	end)
	return Button
end

function Window:_EnableDrag()
	if not self.Draggable then
		return
	end
	local dragging, dragStart, startPos
	self.Header.InputBegan:Connect(function(input)
		if input.UserInputType == Enum.UserInputType.MouseButton1 or input.UserInputType == Enum.UserInputType.Touch then
			dragging = true
			dragStart = input.Position
			startPos = self.Main.Position
		end
	end)
	self.Header.InputChanged:Connect(function(input)
		if dragging and (input.UserInputType == Enum.UserInputType.MouseMovement or input.UserInputType == Enum.UserInputType.Touch) then
			local delta = input.Position - dragStart
			self.Main.Position = UDim2.new(startPos.X.Scale, startPos.X.Offset + delta.X, startPos.Y.Scale, startPos.Y.Offset + delta.Y)
		end
	end)
	self.Header.InputEnded:Connect(function(input)
		if input.UserInputType == Enum.UserInputType.MouseButton1 or input.UserInputType == Enum.UserInputType.Touch then
			dragging = false
		end
	end)
end

function Window:CreateTab(Options)
	Options = Options or {}
	local Tab = TabModule.new(self, Options)
	table.insert(self.Tabs, Tab)
	if not self.ActiveTab then
		self:SelectTab(Tab)
	end
	return Tab
end

function Window:SelectTab(Tab)
	if self.ActiveTab and self.ActiveTab ~= Tab then
		self.ActiveTab:Deselect()
	end
	self.ActiveTab = Tab
	Tab:Select()
end

function Window:ToggleMinimize()
	self.Minimized = not self.Minimized
	self.Body.Visible = not self.Minimized
end

function Window:ToggleMaximize()
	self.Maximized = not self.Maximized
	if self.Maximized then
		self.Main.Size = UDim2.fromScale(0.95, 0.95)
	else
		self.Main.Size = self.Size
	end
end

function Window:Close()
	self.Closed = true
	self.Main.Visible = false
end

function Window:ApplyTheme(Theme)
	self.SubtitleLabel = self.Main:FindFirstChild("Header", true)
end

function Window:Notify(Options)
	Options = Options or {}
	local Theme = self.VoidUI.Themes[self.VoidUI.CurrentTheme]
	local Color = Theme.Text
	if Options.Type == "Success" then Color = Theme.Success
	elseif Options.Type == "Warning" then Color = Theme.Warning
	elseif Options.Type == "Error" then Color = Theme.Danger
	elseif Options.Type == "Info" then Color = Theme.Accent end

	local Notif = Forge.Make("Frame", {
		Name = "Notification",
		BackgroundColor3 = Theme.BackgroundElevated,
		Size = UDim2.new(0, 300, 0, 64),
		AnchorPoint = Vector2.new(1, 0),
		ZIndex = 200,
		Parent = self.NotifFolder,
		Skin = { BackgroundColor3 = "BackgroundElevated" },
	}, {
		Forge.Make("UICorner", { CornerRadius = UDim.new(0, 10) }),
		Forge.Make("UIStroke", { Color = Theme.Border, Thickness = 1, Transparency = 0.4, Skin = { Color = "Border" } }),
		Forge.Make("TextLabel", {
			Text = Options.Title or "Notification",
			TextSize = 14,
			TextXAlignment = Enum.TextXAlignment.Left,
			TextColor3 = Color,
			Size = UDim2.new(1, -20, 0, 20),
			Position = UDim2.new(0, 12, 0, 10),
			FontFace = Font.fromEnum(Enum.Font.Gotham),
		}),
		Forge.Make("TextLabel", {
			Text = Options.Description or "",
			TextSize = 12,
			TextXAlignment = Enum.TextXAlignment.Left,
			TextColor3 = Theme.TextDim,
			Size = UDim2.new(1, -20, 0, 30),
			Position = UDim2.new(0, 12, 0, 32),
			TextWrapped = true,
			Skin = { TextColor3 = "TextDim" },
		}),
	})
	table.insert(self.Notifications, Notif)
	local Tween = Forge.Tween(Notif, 0.3, { BackgroundTransparency = 0 })
	Tween:Play()
	return Notif
end

return Window

end

Modules["Themes.Themes"] = function()
local Themes = {
	Default = {
		Name = "Default",
		Accent = "#7CA2FF",
		AccentGlow = "#9DB8FF",
		Background = "#0E1116",
		BackgroundElevated = "#161B22",
		Surface = "#1C2230",
		SurfaceHover = "#232B3B",
		Border = "#2A3344",
		Text = "#E6EAF2",
		TextDim = "#8A93A6",
		TextMuted = "#5A6377",
		Success = "#3FB950",
		Warning = "#D29922",
		Danger = "#F85149",
		Scrollbar = "#2A3344",
		Gradient = {
			Color = ColorSequence.new({
				ColorSequenceKeypoint.new(0, Color3.fromHex("#1C2230")),
				ColorSequenceKeypoint.new(1, Color3.fromHex("#0E1116")),
			}),
			Transparency = NumberSequence.new(0.85),
		},
		Font = "rbxassetid://12187365364",
		Radius = 12,
		RadiusSmall = 8,
		RadiusLarge = 18,
		HeaderHeight = 52,
		SidebarWidth = 200,
		WindowWidth = 620,
		WindowHeight = 440,
	},
	Midnight = {
		Name = "Midnight",
		Accent = "#5B8DEF",
		AccentGlow = "#7AA5F5",
		Background = "#070A12",
		BackgroundElevated = "#0D1320",
		Surface = "#121A2B",
		SurfaceHover = "#1A2540",
		Border = "#1E2A44",
		Text = "#DCE6F5",
		TextDim = "#7E8AA6",
		TextMuted = "#4A5572",
		Success = "#3FB950",
		Warning = "#D29922",
		Danger = "#F85149",
		Scrollbar = "#1E2A44",
		Gradient = {
			Color = ColorSequence.new({
				ColorSequenceKeypoint.new(0, Color3.fromHex("#121A2B")),
				ColorSequenceKeypoint.new(1, Color3.fromHex("#070A12")),
			}),
			Transparency = NumberSequence.new(0.85),
		},
		Font = "rbxassetid://12187365364",
		Radius = 12,
		RadiusSmall = 8,
		RadiusLarge = 18,
		HeaderHeight = 52,
		SidebarWidth = 200,
		WindowWidth = 620,
		WindowHeight = 440,
	},
	Nebula = {
		Name = "Nebula",
		Accent = "#B57CFF",
		AccentGlow = "#C99FFF",
		Background = "#0C0A16",
		BackgroundElevated = "#15122A",
		Surface = "#1E1A38",
		SurfaceHover = "#2A2450",
		Border = "#2E2850",
		Text = "#ECE6F7",
		TextDim = "#9085B0",
		TextMuted = "#5A5278",
		Success = "#3FB950",
		Warning = "#D29922",
		Danger = "#F85149",
		Scrollbar = "#2E2850",
		Gradient = {
			Color = ColorSequence.new({
				ColorSequenceKeypoint.new(0, Color3.fromHex("#1E1A38")),
				ColorSequenceKeypoint.new(1, Color3.fromHex("#0C0A16")),
			}),
			Transparency = NumberSequence.new(0.85),
		},
		Font = "rbxassetid://12187365364",
		Radius = 14,
		RadiusSmall = 10,
		RadiusLarge = 20,
		HeaderHeight = 54,
		SidebarWidth = 210,
		WindowWidth = 640,
		WindowHeight = 460,
	},
	Crimson = {
		Name = "Crimson",
		Accent = "#FF5C7A",
		AccentGlow = "#FF85A0",
		Background = "#140A0E",
		BackgroundElevated = "#20121A",
		Surface = "#2A1620",
		SurfaceHover = "#3A1E2C",
		Border = "#3E2230",
		Text = "#F7E6EC",
		TextDim = "#B08A98",
		TextMuted = "#785060",
		Success = "#3FB950",
		Warning = "#D29922",
		Danger = "#FF5C7A",
		Scrollbar = "#3E2230",
		Gradient = {
			Color = ColorSequence.new({
				ColorSequenceKeypoint.new(0, Color3.fromHex("#2A1620")),
				ColorSequenceKeypoint.new(1, Color3.fromHex("#140A0E")),
			}),
			Transparency = NumberSequence.new(0.85),
		},
		Font = "rbxassetid://12187365364",
		Radius = 12,
		RadiusSmall = 8,
		RadiusLarge = 18,
		HeaderHeight = 52,
		SidebarWidth = 200,
		WindowWidth = 620,
		WindowHeight = 440,
	},
	Emerald = {
		Name = "Emerald",
		Accent = "#34D399",
		AccentGlow = "#6EE7B7",
		Background = "#07120E",
		BackgroundElevated = "#0E201A",
		Surface = "#13291F",
		SurfaceHover = "#1B3A2C",
		Border = "#1E3A2C",
		Text = "#E2F5EC",
		TextDim = "#84A89A",
		TextMuted = "#4E6E60",
		Success = "#34D399",
		Warning = "#D29922",
		Danger = "#F85149",
		Scrollbar = "#1E3A2C",
		Gradient = {
			Color = ColorSequence.new({
				ColorSequenceKeypoint.new(0, Color3.fromHex("#13291F")),
				ColorSequenceKeypoint.new(1, Color3.fromHex("#07120E")),
			}),
			Transparency = NumberSequence.new(0.85),
		},
		Font = "rbxassetid://12187365364",
		Radius = 12,
		RadiusSmall = 8,
		RadiusLarge = 18,
		HeaderHeight = 52,
		SidebarWidth = 200,
		WindowWidth = 620,
		WindowHeight = 440,
	},
}

local ThemeFallbacks = {
	AccentGlow = "Accent",
	BackgroundElevated = "Background",
	SurfaceHover = "Surface",
	TextDim = "Text",
	TextMuted = "TextDim",
	Border = "Surface",
	Scrollbar = "Border",
	RadiusSmall = "Radius",
	RadiusLarge = "Radius",
}

return Themes, ThemeFallbacks

end

return VoidRequire("init")
